import { DBContext } from "../../../../shared/types/db-context";
import { ICashRegisterRepository } from "../../domain";
import { CreateJournalUseCase } from "./create-journal.use-case";
import { AuditService } from "../../services/audit.service";

export interface CloseRegisterInput {
    actualClosing: number;
    notes?: string;
    reservation?: { amount: number, targetAccountId: string, sourceAccountId?: string };
}

export class CloseRegisterUseCase {
    constructor(
        private readonly registerRepository: ICashRegisterRepository,
        private readonly createJournalUC: CreateJournalUseCase
    ) { }

    async execute(input: CloseRegisterInput, userId: string, dbOrTx?: DBContext): Promise<{ difference: number }> {
        const current = await this.registerRepository.getCurrent(dbOrTx);
        if (!current) {
            throw new Error("No open cash register found");
        }

        // Calculate expected closing
        const transactions = await this.registerRepository.getTransactions(current.id, dbOrTx);
        const netTransactions = transactions.reduce((sum, t) => {
            if (t.type === 'sale' || t.type === 'deposit') return sum + t.amount;
            return sum - t.amount;
        }, 0);

        const expectedClosing = current.openingBalance + netTransactions;
        const difference = input.actualClosing - expectedClosing;

        await this.registerRepository.update(current.id, {
            closedAt: new Date(),
            closedBy: userId,
            expectedClosing,
            actualClosing: input.actualClosing,
            difference,
            status: "closed",
            notes: input.notes || undefined,
        }, dbOrTx);

        // If there is a difference, we post a journal entry for adjustment.
        if (Math.abs(difference) > 0) {
            const isCashOver = difference > 0;
            const cashAccountId = "1-1101"; // Shop Cash
            const adjustmentAccountId = isCashOver ? "4-4900" : "5-5900"; // Misc Income / Misc Expense

            await this.createJournalUC.execute({
                description: `Cash Register Discrepancy Adjustment (${current.id})`,
                referenceType: "cash_register",
                referenceId: current.id,
                lines: [
                    {
                        accountId: isCashOver ? cashAccountId : adjustmentAccountId,
                        debit: Math.abs(difference),
                        credit: 0,
                        description: `Discrepancy: ${isCashOver ? 'Over' : 'Short'}`
                    },
                    {
                        accountId: isCashOver ? adjustmentAccountId : cashAccountId,
                        debit: 0,
                        credit: Math.abs(difference),
                        description: `Discrepancy: ${isCashOver ? 'Over' : 'Short'}`
                    },
                ],
                isAutoGenerated: true,
            }, userId, dbOrTx);
        }

        await AuditService.log({
            userId,
            action: "CLOSE",
            entityType: "cash_register",
            entityId: current.id,
            tableName: "cash_registers",
            newValues: { expectedClosing, actualClosing: input.actualClosing, difference, notes: input.notes, status: "closed" },
        });

        return { difference };
    }
}
