import { DBContext } from "../../../../shared/types/db-context";
import { IAssetRepository, FixedAsset, AssetCategory } from "../../domain";
import { CreateJournalUseCase } from "./create-journal.use-case";
import { AuditService } from "../../services/audit.service";

export interface CreateAssetInput {
    name: string;
    category: AssetCategory;
    purchaseDate: Date;
    purchaseCost: number;
    salvageValue: number;
    usefulLifeMonths: number;
    notes?: string;
    sourceAccountId?: string; // Account used to pay for the asset (e.g., Bank)
}

export class CreateAssetUseCase {
    constructor(
        private readonly assetRepository: IAssetRepository,
        private readonly createJournalUC: CreateJournalUseCase
    ) { }

    async execute(input: CreateAssetInput, userId: string, dbOrTx?: DBContext): Promise<string> {
        const id = `AST-${Date.now()}`;

        // 1. Create Asset Record
        await this.assetRepository.create({
            id,
            ...input,
            currentValue: input.purchaseCost,
            accumulatedDepreciation: 0,
            status: "active",
        }, dbOrTx);

        // 2. Create Journal Entry (Debit Asset, Credit Cash/Bank)
        // Assets usually have specific accounts. For simplicity, we use generic or passed accounts.
        const assetAccountId = "1-1400"; // Fixed Asset parent or specific
        const sourceAccountId = input.sourceAccountId || "1-1100"; // Default Bank

        await this.createJournalUC.execute({
            description: `Purchase of Asset: ${input.name}`,
            referenceType: "asset_purchase",
            referenceId: id,
            lines: [
                { accountId: assetAccountId, debit: input.purchaseCost, credit: 0, description: `Purchase: ${input.name}` },
                { accountId: sourceAccountId, debit: 0, credit: input.purchaseCost, description: `Payment for: ${input.name}` },
            ],
            isAutoGenerated: true,
        }, userId, dbOrTx);

        await AuditService.log({
            userId,
            action: "CREATE",
            entityType: "asset",
            entityId: id,
            tableName: "assets",
            newValues: input as any,
        });

        return id;
    }
}
