import { DBContext } from "../../../../shared/types/db-context";
import { IJournalRepository, IAccountRepository } from "../../domain";
import { AuditService } from "../../services/audit.service";


export interface JournalLineInput {
    accountId: string;
    debit: number;
    credit: number;
    description?: string;
}

export interface CreateJournalInput {
    date?: Date;
    description: string;
    referenceType?: string;
    referenceId?: string;
    lines: JournalLineInput[];
    isAutoGenerated?: boolean;
    createdBy?: string;
}

export class CreateJournalUseCase {
    constructor(
        private readonly journalRepository: IJournalRepository,
        private readonly accountRepository: IAccountRepository
    ) { }

    async execute(input: CreateJournalInput, userId?: string, dbOrTx?: DBContext): Promise<string> {
        const totalDebit = input.lines.reduce((sum, line) => sum + line.debit, 0);
        const totalCredit = input.lines.reduce((sum, line) => sum + line.credit, 0);

        // Tolerance for floating point
        if (Math.abs(totalDebit - totalCredit) > 0.01) {
            throw new Error(`Journal entry not balanced: Debit ${totalDebit} != Credit ${totalCredit}`);
        }

        if (input.lines.length < 2) {
            throw new Error("Journal entry must have at least 2 lines");
        }

        // Generate ID logic is usually in the repo or a domain service. 
        // Here we'll let the repo handle it or pass it.
        const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, "");
        const prefix = `JRN-${dateStr}`;
        const count = await this.journalRepository.countToday(prefix, dbOrTx);
        const journalId = `${prefix}-${String(count + 1).padStart(3, "0")}`;

        await this.journalRepository.create({
            id: journalId,
            date: input.date || new Date(),
            description: input.description,
            referenceType: input.referenceType || undefined,
            referenceId: input.referenceId || undefined,
            status: "posted",
            totalDebit,
            totalCredit,
            isAutoGenerated: input.isAutoGenerated ?? true,
            createdBy: userId || input.createdBy,
            postedBy: userId || input.createdBy,
            postedAt: new Date(),
        }, dbOrTx);

        for (const line of input.lines) {
            await this.journalRepository.createLine({
                journalId,
                accountId: line.accountId,
                debit: line.debit,
                credit: line.credit,
                description: line.description || undefined,
            }, dbOrTx);

            await this.updateAccountBalance(line.accountId, line.debit, line.credit, dbOrTx);
        }

        await AuditService.log({
            userId,
            action: "CREATE",
            entityType: "journal",
            entityId: journalId,
            tableName: "journals",
            newValues: { description: input.description, total: totalDebit, referenceType: input.referenceType || undefined },
        });

        return journalId;
    }

    private async updateAccountBalance(accountId: string, debit: number, credit: number, dbOrTx?: DBContext): Promise<void> {
        const account = await this.accountRepository.findById(accountId, dbOrTx);
        if (!account) throw new Error(`Account ${accountId} not found`);

        const isDebitNormal = account.typeId === "ASSET" || account.typeId === "EXPENSE";
        const netChange = isDebitNormal ? (debit - credit) : (credit - debit);

        await this.accountRepository.update(accountId, {
            balance: account.balance + netChange, // Note: In high currency, avoid simple + in JS. But implementation repo can use sql increment.
            updatedAt: new Date(),
        }, dbOrTx);
    }
}
