import { text, integer, boolean, timestamp, pgTable, json, foreignKey } from "drizzle-orm/pg-core";
import { randomUUID } from "crypto";
import { users } from "../../../users/infrastructure/schema/UserSchema";

const uuid = () => text("id").primaryKey().$defaultFn(() => randomUUID());
const timestamps = () => ({
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").$onUpdate(() => new Date()),
    deletedAt: timestamp("deleted_at"),
});

export const accountTypes = pgTable("account_types", {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    normalBalance: text("normal_balance", { enum: ["debit", "credit"] }).notNull(),
    createdAt: timestamp("created_at").defaultNow(),
});

export const accounts = pgTable("accounts", {
    id: text("id").primaryKey(),
    code: text("code").notNull().unique(),
    name: text("name").notNull(),
    typeId: text("type_id").notNull().references(() => accountTypes.id),
    parentId: text("parent_id"),
    description: text("description"),
    isActive: boolean("is_active").default(true),
    isSystem: boolean("is_system").default(false),
    balance: integer("balance").notNull().default(0),
    ...timestamps(),
}, (table) => ({
    parentReference: foreignKey({
        columns: [table.parentId],
        foreignColumns: [table.id],
        name: "accounts_parent_id_fkey"
    })
}));

export const journals = pgTable("journals", {
    id: text("id").primaryKey(),
    date: timestamp("date").notNull().defaultNow(),
    description: text("description").notNull(),
    referenceType: text("reference_type"),
    referenceId: text("reference_id"),
    status: text("status", { enum: ["draft", "posted", "voided"] }).default("posted"),
    totalDebit: integer("total_debit").notNull().default(0),
    totalCredit: integer("total_credit").notNull().default(0),
    isAutoGenerated: boolean("is_auto_generated").default(true),
    createdBy: text("created_by").references(() => users.id),
    postedBy: text("posted_by").references(() => users.id),
    postedAt: timestamp("posted_at"),
    voidedBy: text("voided_by").references(() => users.id),
    voidedAt: timestamp("voided_at"),
    voidReason: text("void_reason"),
    createdAt: timestamp("created_at").defaultNow(),
});

export const journalLines = pgTable("journal_lines", {
    id: uuid(),
    journalId: text("journal_id").notNull().references(() => journals.id, { onDelete: 'cascade' }),
    accountId: text("account_id").notNull().references(() => accounts.id),
    debit: integer("debit").notNull().default(0),
    credit: integer("credit").notNull().default(0),
    description: text("description"),
    createdAt: timestamp("created_at").defaultNow(),
});

export const assets = pgTable("assets", {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    category: text("category", { enum: ["tool", "equipment", "furniture", "vehicle", "building", "land", "other"] }).notNull(),
    purchaseDate: timestamp("purchase_date").notNull(),
    purchaseCost: integer("purchase_cost").notNull(),
    salvageValue: integer("salvage_value").notNull().default(0),
    usefulLifeMonths: integer("useful_life_months").notNull(),
    depreciationMethod: text("depreciation_method", { enum: ["straight_line"] }).default("straight_line"),
    monthlyDepreciation: integer("monthly_depreciation").notNull().default(0),
    accumulatedDepreciation: integer("accumulated_depreciation").notNull().default(0),
    currentValue: integer("current_value").notNull().default(0),
    status: text("status", { enum: ["active", "disposed", "fully_depreciated"] }).default("active"),
    accountId: text("account_id").references(() => accounts.id),
    depreciationAccountId: text("depreciation_account_id").references(() => accounts.id),
    notes: text("notes"),
    createdBy: text("created_by").references(() => users.id),
    ...timestamps(),
});

export const assetDepreciationLogs = pgTable("asset_depreciation_logs", {
    id: uuid(),
    assetId: text("asset_id").notNull().references(() => assets.id, { onDelete: 'cascade' }),
    period: text("period").notNull(),
    amount: integer("amount").notNull(),
    valueAfter: integer("value_after").notNull(),
    journalId: text("journal_id").references(() => journals.id),
    createdAt: timestamp("created_at").defaultNow(),
});

export const cashRegisters = pgTable("cash_registers", {
    id: text("id").primaryKey(),
    date: timestamp("date").notNull(),
    openedBy: text("opened_by").notNull().references(() => users.id),
    closedBy: text("closed_by").references(() => users.id),
    openingBalance: integer("opening_balance").notNull(),
    expectedClosing: integer("expected_closing").notNull().default(0),
    actualClosing: integer("actual_closing"),
    difference: integer("difference"),
    status: text("status", { enum: ["open", "closed"] }).default("open"),
    notes: text("notes"),
    openedAt: timestamp("opened_at").defaultNow(),
    closedAt: timestamp("closed_at"),
});

export const cashRegisterTransactions = pgTable("cash_register_transactions", {
    id: uuid(),
    registerId: text("register_id").notNull().references(() => cashRegisters.id, { onDelete: 'cascade' }),
    transactionType: text("transaction_type", { enum: ["sale", "service", "expense", "refund", "adjustment"] }).notNull(),
    transactionId: text("transaction_id"),
    paymentMethod: text("payment_method").notNull(),
    amount: integer("amount").notNull(),
    description: text("description"),
    createdAt: timestamp("created_at").defaultNow(),
});

export const revenueTargets = pgTable("revenue_targets", {
    id: uuid(),
    month: text("month").notNull().unique(),
    workingDays: integer("working_days").notNull().default(26),
    monthlyOperational: integer("monthly_operational").notNull().default(0),
    monthlyDepreciation: integer("monthly_depreciation").notNull().default(0),
    monthlyTotal: integer("monthly_total").notNull().default(0),
    dailyBreakeven: integer("daily_breakeven").notNull().default(0),
    profitMarginPercent: integer("profit_margin_percent").notNull().default(20),
    dailyTarget: integer("daily_target").notNull().default(0),
    createdBy: text("created_by").references(() => users.id),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at"),
});

export const operationalCosts = pgTable("operational_costs", {
    id: uuid(),
    category: text("category").notNull(),
    amount: integer("amount").notNull(),
    date: timestamp("date").defaultNow(),
    description: text("description"),
    status: text("status", { enum: ["paid", "pending"] }).default("paid"),
    dueDate: timestamp("due_date"),
    paidAt: timestamp("paid_at"),
    userId: text("user_id").references(() => users.id),
    createdAt: timestamp("created_at").defaultNow(),
});

export const periodLocks = pgTable("period_locks", {
    id: uuid(),
    period: text("period").notNull().unique(),
    status: text("status", { enum: ["open", "closed"] }).default("open"),
    closedBy: text("closed_by").references(() => users.id),
    closedAt: timestamp("closed_at"),
    salesTotal: integer("sales_total").default(0),
    purchasesTotal: integer("purchases_total").default(0),
    expensesTotal: integer("expenses_total").default(0),
    servicesTotal: integer("services_total").default(0),
    createdAt: timestamp("created_at").defaultNow(),
});

export const commissionPayments = pgTable("commission_payments", {
    id: uuid(),
    technicianId: text("technician_id").notNull().references(() => users.id),
    period: text("period").notNull(),
    serviceIds: json("service_ids").$type<string[]>().notNull().default([]),
    amount: integer("amount").notNull(),
    status: text("status", { enum: ["pending", "paid"] }).default("pending"),
    paidBy: text("paid_by").references(() => users.id),
    paidAt: timestamp("paid_at"),
    journalId: text("journal_id").references(() => journals.id),
    accountId: text("account_id").references(() => accounts.id),
    createdAt: timestamp("created_at").defaultNow(),
});

export const auditLogs = pgTable("audit_logs", {
    id: uuid(),
    userId: text("user_id").references(() => users.id),
    action: text("action").notNull(), // CREATE, UPDATE, DELETE, etc.
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    tableName: text("table_name").notNull(),
    oldValues: json("old_values"),
    newValues: json("new_values"),
    reason: text("reason"),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    createdAt: timestamp("created_at").defaultNow(),
});



