import { IAccountingGateway } from "../../domain/purchase-repository.port";
import { accountingService } from "../../../../04-finance/accounting/accounting-container";
import { TransactionContext } from "../../../../../shared/types/db-context";

export class PurchaseAccountingGatewayAdapter implements IAccountingGateway {
    async createJournal(
        tenantId: string,
        params: {
            description: string;
            referenceType: string;
            referenceId: string;
            lines: { accountId: string; debit: number; credit: number; description?: string }[];
            isAutoGenerated?: boolean;
        },
        userId: string,
        tx: TransactionContext
    ): Promise<string> {
        return await accountingService.createJournal(tenantId, params, userId, tx);
    }
}
