import { eq, and, sql, desc, gte, lte } from "drizzle-orm";
import { db } from "../../../../db";
import { accounts, accountTypes, journals, journalLines } from "../../../../db/schema";
import { DBContext } from "../../../../shared/types/db-context";
import { Account, JournalEntry, JournalLine } from "../../domain/entities/ledger.entity";
import { IAccountRepository, IJournalRepository } from "../../domain";
import { AccountTypeDTO } from "../../../../shared/dtos/repositories/accounting";

function mapToAccount(row: any): Account {
    return {
        id: row.id,
        code: row.code,
        name: row.name,
        typeId: row.typeId,
        parentId: row.parentId,
        description: row.description,
        isActive: row.isActive,
        isSystem: row.isSystem,
        balance: Number(row.balance),
        createdAt: row.createdAt,
        updatedAt: row.updatedAt
    };
}

function mapToJournalEntry(row: any): JournalEntry {
    return {
        id: row.id,
        date: row.date,
        description: row.description,
        status: row.status,
        referenceType: row.referenceType,
        referenceId: row.referenceId,
        totalDebit: Number(row.totalDebit || 0),
        totalCredit: Number(row.totalCredit || 0),
        isAutoGenerated: row.isAutoGenerated || false,
        createdBy: row.createdBy,
        postedBy: row.postedBy,
        postedAt: row.postedAt,
        voidedBy: row.voidedBy,
        voidedAt: row.voidedAt,
        voidReason: row.voidReason,
        createdAt: row.createdAt,
        updatedAt: row.updatedAt,
        lines: (row.lines || []).map((line: any) => ({
            id: line.id,
            journalId: line.journalId,
            accountId: line.accountId,
            debit: Number(line.debit || 0),
            credit: Number(line.credit || 0),
            description: line.description
        }))
    };
}

export class AccountRepositoryAdapter implements IAccountRepository {
    async findAll(filters: { typeId?: string }, dbOrTx?: DBContext): Promise<Account[]> {
        const client = (dbOrTx as any) || db;
        const results = await client
            .select({
                id: accounts.id,
                code: accounts.code,
                name: accounts.name,
                typeId: accounts.typeId,
                parentId: accounts.parentId,
                description: accounts.description,
                isActive: accounts.isActive,
                isSystem: accounts.isSystem,
                balance: accounts.balance,
                createdAt: accounts.createdAt,
                updatedAt: accounts.updatedAt,
            })
            .from(accounts)
            .where(filters.typeId ? eq(accounts.typeId, filters.typeId) : undefined)
            .orderBy(accounts.code);

        return results.map(mapToAccount);
    }

    async findById(id: string, dbOrTx?: DBContext): Promise<Account | null> {
        const client = (dbOrTx as any) || db;
        const [result] = await client.select().from(accounts).where(eq(accounts.id, id));
        return result ? mapToAccount(result) : null;
    }

    async findByCode(code: string, dbOrTx?: DBContext): Promise<Account | null> {
        const client = (dbOrTx as any) || db;
        const [result] = await client.select().from(accounts).where(eq(accounts.code, code));
        return result ? mapToAccount(result) : null;
    }

    async findTypes(dbOrTx?: DBContext): Promise<AccountTypeDTO[]> {
        const client = (dbOrTx as any) || db;
        const results = await client.query.accountTypes.findMany();
        return results as AccountTypeDTO[];
    }

    async findTypeById(id: string, dbOrTx?: DBContext): Promise<AccountTypeDTO | null> {
        const client = (dbOrTx as any) || db;
        const result = await client.query.accountTypes.findFirst({
            where: eq(accountTypes.id, id)
        });
        return result ? result as AccountTypeDTO : null;
    }

    async create(data: Partial<Account>, dbOrTx?: DBContext): Promise<{ id: string }> {
        const client = (dbOrTx as any) || db;
        const [result] = await client.insert(accounts).values(data).returning({ id: accounts.id });
        return result;
    }

    async update(id: string, data: Partial<Account>, dbOrTx?: DBContext): Promise<void> {
        const client = (dbOrTx as any) || db;
        await client.update(accounts).set(data).where(eq(accounts.id, id));
    }

    async delete(id: string, dbOrTx?: DBContext): Promise<void> {
        const client = (dbOrTx as any) || db;
        await client.delete(accounts).where(eq(accounts.id, id));
    }
}

export class JournalRepositoryAdapter implements IJournalRepository {
    async findAll(filters: any, dbOrTx?: DBContext): Promise<JournalEntry[]> {
        const client = (dbOrTx as any) || db;
        let where = and();
        if (filters.startDate) where = and(where, gte(journals.date, new Date(filters.startDate)));
        if (filters.endDate) where = and(where, lte(journals.date, new Date(filters.endDate)));
        if (filters.status) where = and(where, eq(journals.status, filters.status));

        const results = await client
            .select()
            .from(journals)
            .where(where)
            .orderBy(desc(journals.date))
            .limit(filters.limit || 50)
            .offset(filters.offset || 0);

        return results.map(mapToJournalEntry);
    }

    async findById(id: string, dbOrTx?: DBContext): Promise<JournalEntry | null> {
        const client = (dbOrTx as any) || db;
        const [journal] = await client.select().from(journals).where(eq(journals.id, id));
        if (!journal) return null;

        const lines = await client
            .select({
                id: journalLines.id,
                accountId: journalLines.accountId,
                debit: journalLines.debit,
                credit: journalLines.credit,
                description: journalLines.description,
            })
            .from(journalLines)
            .where(eq(journalLines.journalId, id));

        return mapToJournalEntry({ ...journal, lines });
    }

    async countToday(prefix: string, dbOrTx?: DBContext): Promise<number> {
        const client = (dbOrTx as any) || db;
        const result = await client
            .select({ count: sql<number>`count(*)` })
            .from(journals)
            .where(sql`${journals.id} LIKE ${prefix + '%'}`);
        return Number(result[0]?.count || 0);
    }

    async create(data: Partial<JournalEntry>, dbOrTx?: DBContext): Promise<void> {
        const client = (dbOrTx as any) || db;
        await client.insert(journals).values(data);
    }

    async createLine(data: Partial<JournalLine>, dbOrTx?: DBContext): Promise<void> {
        const client = (dbOrTx as any) || db;
        await client.insert(journalLines).values(data);
    }

    async update(id: string, data: Partial<JournalEntry>, dbOrTx?: DBContext): Promise<void> {
        const client = (dbOrTx as any) || db;
        await client.update(journals).set(data).where(eq(journals.id, id));
    }

    async delete(id: string, dbOrTx?: DBContext): Promise<void> {
        const client = (dbOrTx as any) || db;
        await client.delete(journals).where(eq(journals.id, id));
    }

    async deleteByReference(type: string, id: string, dbOrTx?: DBContext): Promise<void> {
        const client = (dbOrTx as any) || db;
        await client.delete(journals).where(and(eq(journals.referenceType, type as any), eq(journals.referenceId, id)));
    }
}
