import { PurchaseOrder } from "./entities/purchase.entity";

export interface IPurchaseRepository {
    findById(id: string, dbOrTx?: unknown): Promise<PurchaseOrder | null>;
    save(purchase: PurchaseOrder, dbOrTx?: unknown): Promise<void>;
    findAll(filters?: any, dbOrTx?: unknown): Promise<PurchaseOrder[]>;
    delete(id: string, dbOrTx?: unknown): Promise<void>;
}

export interface IPurchasePaymentRepository {
    savePayment(payment: any, dbOrTx?: unknown): Promise<void>;
    findPaymentsByPurchaseId(purchaseId: string): Promise<any[]>;
}

export interface IActivityLogger {
    log(entry: {
        userId: string;
        action: string;
        entityType: string;
        entityId: string;
        description: string;
    }, dbOrTx?: unknown): Promise<void>;
}

export interface INotificationGateway {
    notifyPurchaseOrderCreated(
        payload: { purchaseId: string; userId: string; supplierId: string },
        dbOrTx?: unknown
    ): Promise<void>;

    notifyGoodsReceived(
        payload: { purchaseId: string; userId: string; hasDiscrepancy: boolean },
        dbOrTx?: unknown
    ): Promise<void>;
}

export interface IPurchaseVariantPolicyGateway {
    ensureVariantAllowedForSupplier(
        params: { productId: string; variantName: string; supplierId: string },
        dbOrTx?: unknown
    ): Promise<void>;
}

export interface IAccountingGateway {
    createJournal(params: {
        description: string;
        referenceType: string;
        referenceId: string;
        lines: { accountId: string; debit: number; credit: number; description?: string }[];
        isAutoGenerated?: boolean;
    }, userId?: string, dbOrTx?: unknown): Promise<string>;
}
