import { PurchaseOrder } from "./entities/purchase.entity";
import { TransactionContext } from "../../../../shared/types/db-context";

export interface IPurchaseRepository {
    findById(tenantId: string, id: string, tx: TransactionContext): Promise<PurchaseOrder | null>;
    save(tenantId: string, purchase: PurchaseOrder, tx: TransactionContext): Promise<void>;
    findAll(tenantId: string, filters: any, tx: TransactionContext): Promise<PurchaseOrder[]>;
    delete(tenantId: string, id: string, tx: TransactionContext): Promise<void>;
}

export interface IPurchasePaymentRepository {
    savePayment(tenantId: string, payment: any, tx: TransactionContext): Promise<void>;
    findPaymentsByPurchaseId(tenantId: string, purchaseId: string, tx: TransactionContext): Promise<any[]>;
}

export interface IActivityLogger {
    log(tenantId: string, entry: {
        userId: string;
        action: string;
        entityType: string;
        entityId: string;
        description: string;
    }, tx: TransactionContext): Promise<void>;
}

export interface INotificationGateway {
    notifyPurchaseOrderCreated(
        tenantId: string,
        payload: { purchaseId: string; userId: string; supplierId: string },
        tx: TransactionContext
    ): Promise<void>;

    notifyGoodsReceived(
        tenantId: string,
        payload: { purchaseId: string; userId: string; hasDiscrepancy: boolean },
        tx: TransactionContext
    ): Promise<void>;
}

export interface IPurchaseVariantPolicyGateway {
    ensureVariantAllowedForSupplier(
        tenantId: string,
        params: { productId: string; variantName: string; supplierId: string },
        tx: TransactionContext
    ): Promise<void>;
}

export interface IAccountingGateway {
    createJournal(
        tenantId: string,
        params: {
            description: string;
            referenceType: string;
            referenceId: string;
            lines: { accountId: string; debit: number; credit: number; description?: string }[];
            isAutoGenerated?: boolean;
        },
        userId: string,
        tx: TransactionContext
    ): Promise<string>;
}
