import { vi } from "vitest";
import type { Context } from "hono";
import * as schema from "../src/shared/infrastructure/database/schema";
import { type InferInsertModel, type InferSelectModel } from "drizzle-orm";

// Simple "Faker-like" helpers to generate random data
const faker = {
    string: {
        uuid: () => crypto.randomUUID(),
        alphanumeric: (length: number = 8) => Math.random().toString(36).substring(2, 2 + length),
        numeric: (length: number = 4) => Math.floor(Math.random() * Math.pow(10, length)).toString().padStart(length, "0"),
    },
    number: {
        int: (min: number = 1, max: number = 1000) => Math.floor(Math.random() * (max - min + 1)) + min,
        price: () => Math.floor(Math.random() * 10000) * 1000,
        quantity: () => Math.floor(Math.random() * 50) + 1,
    },
    date: {
        past: () => new Date(Date.now() - Math.floor(Math.random() * 10000000000)),
        future: () => new Date(Date.now() + Math.floor(Math.random() * 10000000000)),
        recent: () => new Date(Date.now() - Math.floor(Math.random() * 86400000 * 7)),
    },
    person: {
        firstName: () => {
            const names = ["John", "Jane", "Alice", "Bob", "Charlie", "David", "Eve", "Frank"];
            return names[Math.floor(Math.random() * names.length)] as string;
        },
        fullName: () => {
            const first = ["John", "Jane", "Alice", "Bob", "Charlie", "David", "Eve", "Frank"];
            const last = ["Doe", "Smith", "Johnson", "Brown", "Williams", "Jones", "Miller", "Davis"];
            const f = first[Math.floor(Math.random() * first.length)] as string;
            const l = last[Math.floor(Math.random() * last.length)] as string;
            return `${f} ${l}`;
        },
    },
    company: {
        name: () => {
            const names = ["Acme Corp", "Tech Solutions", "Global Gadgets", "Smart Systems", "Innovative Tech"];
            return names[Math.floor(Math.random() * names.length)] as string;
        },
    },
    helpers: {
        arrayElement: <T>(array: T[]): T => array[Math.floor(Math.random() * array.length)] as T,
    },
};

/**
 * Mocks the Hono Context for testing controllers.
 */
export const createMockContext = () => {
    const req = {
        param: vi.fn(),
        query: vi.fn().mockReturnValue({}),
        header: vi.fn(),
        json: vi.fn(),
        valid: vi.fn(),
    };

    const res = {
        headers: new Headers(),
    };

    const items: Record<string, unknown> = {};

    return {
        req,
        res,
        header: vi.fn(),
        status: vi.fn(),
        json: vi.fn().mockImplementation((data: any, status?: number) => ({
            status: status || 200,
            json: async () => data,
        })),
        body: vi.fn(),
        text: vi.fn(),
        env: {},
        var: items,
        get: (key: string) => items[key],
        set: (key: string, value: unknown) => { items[key] = value; },
        executionCtx: {
            waitUntil: vi.fn(),
            passThroughOnException: vi.fn(),
        },
    } as unknown as Context;
};

// ============================================
// USERS & AUTH
// ============================================

export const createMockRole = (overrides?: Partial<InferInsertModel<typeof schema.roles>>) => {
    return {
        id: faker.string.alphanumeric(5),
        name: faker.helpers.arrayElement(["Administrator", "Technician", "Cashier"]),
        permissions: [],
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.roles>;
};

export const createMockUser = (overrides?: Partial<InferInsertModel<typeof schema.users>>) => {
    const role = overrides?.role || createMockRole().id;
    return {
        id: faker.string.uuid(),
        username: faker.person.firstName().toLowerCase() + faker.string.numeric(3),
        password: "hashed_password_placeholder",
        role,
        name: faker.person.fullName(),
        isActive: true,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.users>;
};

// ============================================
// MASTER DATA
// ============================================

export const createMockCategory = (overrides?: Partial<InferInsertModel<typeof schema.categories>>) => {
    return {
        id: faker.string.uuid(),
        name: faker.helpers.arrayElement(["Smartphones", "Accessories", "Spare Parts", "Services"]),
        description: "Autogenerated category",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.categories>;
};

export const createMockSupplier = (overrides?: Partial<InferInsertModel<typeof schema.suppliers>>) => {
    return {
        id: `SUP-${faker.string.numeric(3)}`,
        name: faker.company.name(),
        contact: faker.person.fullName(),
        phone: `08${faker.string.numeric(10)}`,
        address: "123 Tech Street",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.suppliers>;
};

export const createMockMember = (overrides?: Partial<InferInsertModel<typeof schema.members>>) => {
    return {
        id: `MBR-${faker.string.numeric(3)}`,
        name: faker.person.fullName(),
        phone: `08${faker.string.numeric(10)}`,
        email: `${faker.string.alphanumeric(8)}@example.com`,
        discountPercent: 0,
        points: 0,
        debt: 0,
        creditLimit: 0,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.members>;
};

export const createMockCategoryVariant = (overrides?: Partial<InferInsertModel<typeof schema.categoryVariants>>) => {
    const categoryId = overrides?.categoryId || createMockCategory().id;
    return {
        categoryId,
        name: faker.helpers.arrayElement(["Color", "Size", "Storage"]),
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.categoryVariants>;
};

export const createMockSupplierCategory = (overrides?: Partial<InferInsertModel<typeof schema.supplierCategories>>) => {
    const supplierId = overrides?.supplierId || createMockSupplier().id;
    const categoryId = overrides?.categoryId || createMockCategory().id;
    return {
        supplierId,
        categoryId,
        ...overrides,
    } as InferSelectModel<typeof schema.supplierCategories>;
};

// ============================================
// INVENTORY
// ============================================

export const createMockProduct = (overrides?: Partial<InferInsertModel<typeof schema.products>>) => {
    const categoryId = overrides?.categoryId || createMockCategory().id;
    return {
        id: `PRD-${faker.string.numeric(3)}`,
        code: faker.string.alphanumeric(10).toUpperCase(),
        name: `Product ${faker.string.alphanumeric(3)}`,
        categoryId,
        stock: faker.number.quantity(),
        minStock: 5,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.products>;
};

export const createMockProductVariant = (overrides?: Partial<InferInsertModel<typeof schema.productVariants>>) => {
    const productId = overrides?.productId || createMockProduct().id;
    return {
        id: `VAR-${faker.string.numeric(3)}`,
        productId,
        name: faker.helpers.arrayElement(["Black", "White", "128GB", "256GB"]),
        defaultPrice: faker.number.price(),
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.productVariants>;
};

export const createMockProductBatch = (overrides?: Partial<InferInsertModel<typeof schema.productBatches>>) => {
    const productId = overrides?.productId || createMockProduct().id;
    const buyPrice = faker.number.price();
    return {
        id: `B-${faker.string.numeric(3)}`,
        productId,
        buyPrice,
        sellPrice: Math.floor(buyPrice * 1.2),
        initialStock: 100,
        currentStock: 100,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.productBatches>;
};

// ============================================
// PURCHASES (Stock In)
// ============================================

export const createMockPurchase = (overrides?: Partial<InferInsertModel<typeof schema.purchases>>) => {
    const supplierId = overrides?.supplierId || createMockSupplier().id;
    const totalAmount = overrides?.totalAmount || faker.number.price() * 5;
    return {
        id: `PO-${faker.string.numeric(4)}`,
        supplierId,
        totalAmount,
        date: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.purchases>;
};

export const createMockPurchaseItem = (overrides?: Partial<InferInsertModel<typeof schema.purchaseItems>>) => {
    const purchaseId = overrides?.purchaseId || createMockPurchase().id;
    const productId = overrides?.productId || createMockProduct().id;
    const buyPrice = faker.number.price();
    return {
        purchaseId,
        productId,
        qtyOrdered: 10,
        qtyReceived: 10,
        buyPrice,
        sellPrice: Math.floor(buyPrice * 1.2),
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.purchaseItems>;
};

// ============================================
// SALES (Stock Out)
// ============================================

export const createMockSale = (overrides?: Partial<InferInsertModel<typeof schema.sales>>) => {
    const userId = overrides?.userId || createMockUser().id;
    return {
        id: `SAL-${faker.string.numeric(4)}`,
        userId,
        totalAmount: faker.number.price() * 2,
        discountAmount: 0,
        paymentMethod: "cash",
        paymentStatus: "paid",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.sales>;
};

export const createMockSaleItem = (overrides?: Partial<InferInsertModel<typeof schema.saleItems>>) => {
    const saleId = overrides?.saleId || createMockSale().id;
    const productId = overrides?.productId || createMockProduct().id;
    const batchId = overrides?.batchId || createMockProductBatch({ productId }).id;
    return {
        saleId,
        productId,
        batchId,
        qty: 1,
        price: faker.number.price(),
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.saleItems>;
};

// ============================================
// DEVICES
// ============================================

export const createMockDevice = (overrides?: Partial<InferInsertModel<typeof schema.devices>>) => {
    return {
        id: `DEV-${faker.string.numeric(3)}`,
        brand: "Generic Brand",
        model: `Model ${faker.string.numeric(2)}`,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.devices>;
};

export const createMockBrand = (overrides?: Partial<InferInsertModel<typeof schema.brands>>) => {
    return {
        id: faker.string.alphanumeric(4),
        name: "Generic Brand",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.brands>;
};

export const createMockProductDeviceCompatibility = (overrides?: Partial<InferInsertModel<typeof schema.productDeviceCompatibility>>) => {
    const productId = overrides?.productId || createMockProduct().id;
    const deviceId = overrides?.deviceId || createMockDevice().id;
    return {
        productId,
        deviceId,
        ...overrides,
    } as InferSelectModel<typeof schema.productDeviceCompatibility>;
};

// ============================================
// SERVICE
// ============================================

export const createMockService = (overrides?: Partial<InferInsertModel<typeof schema.services>>) => {
    return {
        no: `SRV-${faker.date.recent().getFullYear()}-${faker.string.numeric(3)}`,
        customer: {
            name: faker.person.fullName(),
            phone: `08${faker.string.numeric(10)}`,
        },
        device: {
            brand: "Generic",
            model: "Phone",
        },
        complaint: "Broken screen",
        status: "antrian",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.services>;
};

// ============================================
// ACTIVITY LOGS & NOTIFICATIONS
// ============================================

export const createMockActivityLog = (overrides?: Partial<InferInsertModel<typeof schema.activityLogs>>) => {
    const userId = overrides?.userId || createMockUser().id;
    return {
        userId,
        action: "CREATE",
        entityType: "service",
        entityId: faker.string.alphanumeric(5),
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.activityLogs>;
};

export const createMockNotification = (overrides?: Partial<InferInsertModel<typeof schema.notifications>>) => {
    const userId = overrides?.userId || createMockUser().id;
    return {
        userId,
        type: "new_assignment",
        title: "New Assignment",
        message: "You have a new task.",
        isRead: false,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.notifications>;
};

// ============================================
// SETTINGS
// ============================================

export const createMockSetting = (overrides?: Partial<InferInsertModel<typeof schema.settings>>) => {
    return {
        key: faker.string.alphanumeric(8),
        value: { val: "test" },
        ...overrides,
    } as InferSelectModel<typeof schema.settings>;
};

// ============================================
// PAYMENT METHODS
// ============================================

export const createMockPaymentMethod = (overrides?: Partial<InferInsertModel<typeof schema.paymentMethods>>) => {
    return {
        id: faker.string.uuid(),
        name: "Cash",
        type: "cash",
        enabled: true,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.paymentMethods>;
};

export const createMockPaymentVariant = (overrides?: Partial<InferInsertModel<typeof schema.paymentVariants>>) => {
    const methodId = overrides?.methodId || createMockPaymentMethod().id;
    return {
        id: faker.string.uuid(),
        methodId,
        name: "Main Register",
        enabled: true,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.paymentVariants>;
};

export const createMockSalePayment = (overrides?: Partial<InferInsertModel<typeof schema.salePayments>>) => {
    const saleId = overrides?.saleId || createMockSale().id;
    return {
        saleId,
        amount: faker.number.price(),
        method: "Cash",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.salePayments>;
};

// ============================================
// PURCHASE RETURNS
// ============================================

export const createMockPurchaseReturn = (overrides?: Partial<InferInsertModel<typeof schema.purchaseReturns>>) => {
    const supplierId = overrides?.supplierId || createMockSupplier().id;
    const userId = overrides?.userId || createMockUser().id;
    return {
        id: `RET-${faker.string.numeric(3)}`,
        supplierId,
        userId,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.purchaseReturns>;
};

export const createMockPurchaseReturnItem = (overrides?: Partial<InferInsertModel<typeof schema.purchaseReturnItems>>) => {
    const returnId = overrides?.returnId || createMockPurchaseReturn().id;
    const productId = overrides?.productId || createMockProduct().id;
    const batchId = overrides?.batchId || createMockProductBatch({ productId }).id;
    return {
        returnId,
        productId,
        batchId,
        qty: 1,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.purchaseReturnItems>;
};

// ============================================
// DEFECTIVE ITEMS
// ============================================

export const createMockDefectiveItem = (overrides?: Partial<InferInsertModel<typeof schema.defectiveItems>>) => {
    const productId = overrides?.productId || createMockProduct().id;
    const batchId = overrides?.batchId || createMockProductBatch({ productId }).id;
    const supplierId = overrides?.supplierId || createMockSupplier().id;
    return {
        id: `DEF-${faker.string.numeric(3)}`,
        productId,
        batchId,
        supplierId,
        qty: 1,
        source: "manual",
        status: "pending",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.defectiveItems>;
};

// ============================================
// OPERATIONAL COSTS
// ============================================

export const createMockOperationalCost = (overrides?: Partial<InferInsertModel<typeof schema.operationalCosts>>) => {
    return {
        category: "Lainnya",
        amount: faker.number.price(),
        description: "Misc cost",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.operationalCosts>;
};

// ============================================
// SERVICE TOOLS
// ============================================

export const createMockServiceTool = (overrides?: Partial<InferInsertModel<typeof schema.serviceTools>>) => {
    return {
        id: `TOOL-${faker.string.numeric(3)}`,
        name: "Screwdriver",
        qty: 1,
        condition: "good",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.serviceTools>;
};

// ============================================
// STOCK OPNAME
// ============================================

export const createMockStockOpnameSession = (overrides?: Partial<InferInsertModel<typeof schema.stockOpnameSessions>>) => {
    const userId = overrides?.userId || createMockUser().id;
    return {
        id: `SO-${faker.string.numeric(8)}-${faker.string.numeric(3)}`,
        status: "draft",
        userId,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.stockOpnameSessions>;
};

export const createMockStockOpnameItem = (overrides?: Partial<InferInsertModel<typeof schema.stockOpnameItems>>) => {
    const sessionId = overrides?.sessionId || createMockStockOpnameSession().id;
    const productId = overrides?.productId || createMockProduct().id;
    return {
        sessionId,
        productId,
        systemStock: 10,
        ...overrides,
    } as InferSelectModel<typeof schema.stockOpnameItems>;
};

// ============================================
// ACCOUNTING
// ============================================

export const createMockAccountType = (overrides?: Partial<InferInsertModel<typeof schema.accountTypes>>) => {
    return {
        id: faker.string.alphanumeric(5),
        name: "Assets",
        normalBalance: "debit",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.accountTypes>;
};

export const createMockAccount = (overrides?: Partial<InferInsertModel<typeof schema.accounts>>) => {
    const typeId = overrides?.typeId || createMockAccountType().id;
    return {
        id: faker.string.numeric(5),
        code: faker.string.numeric(4),
        name: "Cash",
        typeId,
        balance: 0,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.accounts>;
};

export const createMockJournal = (overrides?: Partial<InferInsertModel<typeof schema.journals>>) => {
    return {
        id: `JRN-${faker.string.numeric(8)}-${faker.string.numeric(3)}`,
        description: "Journal Entry",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.journals>;
};

export const createMockJournalLine = (overrides?: Partial<InferInsertModel<typeof schema.journalLines>>) => {
    const journalId = overrides?.journalId || createMockJournal().id;
    const accountId = overrides?.accountId || createMockAccount().id;
    return {
        journalId,
        accountId,
        debit: 0,
        credit: 0,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.journalLines>;
};

export const createMockAsset = (overrides?: Partial<InferInsertModel<typeof schema.assets>>) => {
    return {
        id: `AST-${faker.string.numeric(3)}`,
        name: "Office Chair",
        category: "furniture",
        purchaseDate: new Date(),
        purchaseCost: 1000000,
        usefulLifeMonths: 60,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.assets>;
};

export const createMockAssetDepreciationLog = (overrides?: Partial<InferInsertModel<typeof schema.assetDepreciationLogs>>) => {
    const assetId = overrides?.assetId || createMockAsset().id;
    return {
        assetId,
        period: "2026-01",
        amount: 1000,
        valueAfter: 999000,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.assetDepreciationLogs>;
};

export const createMockCashRegister = (overrides?: Partial<InferInsertModel<typeof schema.cashRegisters>>) => {
    const openedBy = overrides?.openedBy || createMockUser().id;
    return {
        id: `REG-${faker.string.numeric(8)}-${faker.string.numeric(3)}`,
        date: new Date(),
        openedBy,
        openingBalance: 0,
        ...overrides,
    } as InferSelectModel<typeof schema.cashRegisters>;
};

export const createMockCashRegisterTransaction = (overrides?: Partial<InferInsertModel<typeof schema.cashRegisterTransactions>>) => {
    const registerId = overrides?.registerId || createMockCashRegister().id;
    return {
        registerId,
        transactionType: "sale",
        paymentMethod: "Cash",
        amount: 1000,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.cashRegisterTransactions>;
};

export const createMockRevenueTarget = (overrides?: Partial<InferInsertModel<typeof schema.revenueTargets>>) => {
    return {
        month: "2026-01",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.revenueTargets>;
};

export const createMockPurchasePayment = (overrides?: Partial<InferInsertModel<typeof schema.purchasePayments>>) => {
    const purchaseId = overrides?.purchaseId || createMockPurchase().id;
    const supplierId = overrides?.supplierId || createMockSupplier().id;
    return {
        purchaseId,
        supplierId,
        amount: 1000,
        method: "transfer",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.purchasePayments>;
};

export const createMockPeriodLock = (overrides?: Partial<InferInsertModel<typeof schema.periodLocks>>) => {
    return {
        period: "2026-01",
        status: "open",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.periodLocks>;
};

export const createMockCommissionPayment = (overrides?: Partial<InferInsertModel<typeof schema.commissionPayments>>) => {
    const technicianId = overrides?.technicianId || createMockUser().id;
    return {
        technicianId,
        period: "2026-01",
        amount: 1000,
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.commissionPayments>;
};

export const createMockAuditLog = (overrides?: Partial<InferInsertModel<typeof schema.auditLogs>>) => {
    return {
        action: "CREATE",
        entityType: "unknown",
        entityId: faker.string.alphanumeric(5),
        tableName: "unknown",
        createdAt: new Date(),
        ...overrides,
    } as InferSelectModel<typeof schema.auditLogs>;
};
