import { TransactionContext } from "../../../../shared/types/db-context";
import { services, users } from "../../../../shared/infrastructure/database/schema";
import { eq, and, gte, lte } from "drizzle-orm";
import { accountingService } from "../accounting-container";
import { ICommissionPaymentRepository } from "../domain";

const commissionRepository = (accountingService as any).commissionRepository as ICommissionPaymentRepository;

export interface CreateCommissionPaymentInput {
    technicianId: string;
    period: string;
    serviceIds: string[];
    amount: number;
    accountId?: string;
}

export class CommissionPaymentService {
    /**
     * Get pending commissions by technician for a period
     */
    static async getPendingCommissions(tenantId: string, tx: TransactionContext, period: string) {
        const startDate = new Date(`${period}-01`);
        const endDate = new Date(startDate);
        endDate.setMonth(endDate.getMonth() + 1);

        // Get all completed services in this period
        const completedServices = await tx
            .select({
                id: services.id,
                no: services.no,
                technicianId: services.technicianId,
                technicianName: users.name,
                actualCost: services.actualCost,
                parts: services.parts,
                dateOut: services.dateOut,
                commissionConfig: users.commissionConfig,
            })
            .from(services)
            .leftJoin(users, eq(services.technicianId, users.id))
            .where(and(
                eq(services.tenantId, tenantId),
                gte(services.dateOut, startDate),
                lte(services.dateOut, endDate),
                eq(services.status, "diambil")
            ));

        // Get already paid service IDs for this period
        const paidServiceIds = await commissionRepository.getPaidServiceIds(tenantId, period, tx);

        // Filter out already paid services and group by technician
        const pendingByTechnician: Record<string, {
            technicianId: string;
            technicianName: string;
            services: (typeof completedServices)[0][];
            totalAmount: number;
        }> = {};

        for (const svc of completedServices) {
            const techId = svc.technicianId;
            if (!techId || paidServiceIds.has(svc.id)) continue;

            if (!pendingByTechnician[techId]) {
                pendingByTechnician[techId] = {
                    technicianId: techId,
                    technicianName: svc.technicianName || "Unknown",
                    services: [],
                    totalAmount: 0,
                };
            }

            // Special Commission Calculation:
            // (Service Price - Spare Part Selling Price) * Commission %

            const servicePrice = svc.actualCost || 0;
            let partsSellingPrice = 0;

            if (svc.parts && Array.isArray(svc.parts)) {
                for (const part of svc.parts as any[]) {
                    // Assuming part.price is the selling price charged to customer
                    // If part.price is missing, fallback to 0 to avoid NaN
                    const price = Number(part.price) || 0;
                    const qty = Number(part.qty) || 1;
                    partsSellingPrice += price * qty;
                }
            }

            const netServiceRevenue = Math.max(0, servicePrice - partsSellingPrice);

            // Get Commission Rate
            // Default 10% if not configured
            let rate = 10;
            const config = svc.commissionConfig as any;
            if (config && typeof config === 'object' && config.rate !== undefined) {
                rate = Number(config.rate);
            }

            const commission = Math.floor(netServiceRevenue * (rate / 100));

            pendingByTechnician[techId].services.push(svc);
            pendingByTechnician[techId].totalAmount += commission;
        }

        return Object.values(pendingByTechnician);
    }

    static async payCommission(tenantId: string, tx: TransactionContext, input: CreateCommissionPaymentInput, userId: string): Promise<string> {
        const accountId = input.accountId || "1-1001"; // Default: Kas Toko

        // Create journal entry via facade
        await accountingService.createJournal(tenantId, {
            description: `Komisi teknisi ${input.period}`,
            referenceType: "commission",
            referenceId: input.technicianId,
            lines: [
                { accountId: "5-2005", debit: input.amount, credit: 0, description: "Beban komisi" },
                { accountId, debit: 0, credit: input.amount, description: "Pembayaran kas" },
            ],
            isAutoGenerated: true
        }, userId, tx);

        const journalId = `JRN-COM-${Date.now()}`;

        // Insert payment record via repo
        const { id } = await commissionRepository.create(tenantId, {
            technicianId: input.technicianId,
            period: input.period,
            serviceIds: input.serviceIds,
            amount: input.amount,
            status: "paid",
            paidBy: userId,
            paidAt: new Date(),
            journalId,
            accountId,
        }, tx);

        return id;
    }

    /**
     * Get commission payment history
     */
    static async getPaymentHistory(tenantId: string, tx: TransactionContext, technicianId?: string, period?: string) {
        return await commissionRepository.findHistory(tenantId, tx, technicianId, period);
    }

    /**
     * Get summary for a period
     */
    static async getPeriodSummary(tenantId: string, tx: TransactionContext, period: string) {
        const pending = await this.getPendingCommissions(tenantId, tx, period);
        const paid = await this.getPaymentHistory(tenantId, tx, undefined, period);

        return {
            period,
            pendingCount: pending.length,
            pendingTotal: pending.reduce((s, p) => s + p.totalAmount, 0),
            paidCount: paid.length,
            paidTotal: paid.reduce((s, p) => s + p.amount, 0),
        };
    }
}
