import { accountingService } from "../accounting-container";
import { IJournalRepository } from "../domain";
import { TransactionContext } from "../../../../shared/types/db-context";

export type JournalReferenceType = "sale" | "purchase" | "expense" | "service" | "depreciation" | "commission" | "supplier_payment" | "adjustment" | "asset_purchase";

export interface JournalLineInput {
    accountId: string;
    debit: number;
    credit: number;
    description?: string;
}

export interface CreateJournalInput {
    date?: Date;
    description: string;
    referenceType?: JournalReferenceType;
    referenceId?: string;
    lines: JournalLineInput[];
    isAutoGenerated?: boolean;
    createdBy?: string;
}

// Redirect legacy JournalService to the AccountingService facade
const journalRepo = (accountingService as any).journalRepository as IJournalRepository;

export class JournalService {
    static async create(input: CreateJournalInput, userId?: string, tx?: TransactionContext, tenantId?: string): Promise<string> {
        return await accountingService.createJournal(tenantId || "default", input, userId, tx);
    }

    static async getAll(filters: any = {}, tx?: TransactionContext, tenantId?: string) {
        return await accountingService.getAllJournals(tenantId || "default", filters, tx);
    }

    static async getById(journalId: string, tx?: TransactionContext, tenantId?: string) {
        return await accountingService.getJournalById(tenantId || "default", journalId, tx);
    }

    static async deleteByReference(type: string, id: string, tx?: TransactionContext, tenantId?: string): Promise<void> {
        await journalRepo.deleteByReference(tenantId || "default", type, id, tx!);
    }
}
