import { accountingService } from "../accounting-container";
import { IJournalRepository } from "../domain";

export type JournalReferenceType = "sale" | "purchase" | "expense" | "service" | "depreciation" | "commission" | "supplier_payment" | "adjustment" | "asset_purchase";

export interface JournalLineInput {
    accountId: string;
    debit: number;
    credit: number;
    description?: string;
}

export interface CreateJournalInput {
    date?: Date;
    description: string;
    referenceType?: JournalReferenceType;
    referenceId?: string;
    lines: JournalLineInput[];
    isAutoGenerated?: boolean;
    createdBy?: string;
}

// Redirect legacy JournalService to the AccountingService facade
const journalRepo = (accountingService as any).journalRepository as IJournalRepository;

export class JournalService {
    static async create(input: CreateJournalInput, userId?: string, dbOrTx?: any): Promise<string> {
        return await accountingService.createJournal(input, userId, dbOrTx);
    }

    static async getAll(filters: any = {}, dbOrTx?: any) {
        return await accountingService.getAllJournals(filters, dbOrTx);
    }

    static async getById(journalId: string, dbOrTx?: any) {
        return await accountingService.getJournalById(journalId, dbOrTx);
    }

    static async deleteByReference(type: string, id: string, userId?: string, dbOrTx?: any): Promise<void> {
        await journalRepo.deleteByReference(type, id, dbOrTx);
    }
}
