import { DBContext } from "../../../../shared/types/db-context";
import { IAccountingGateway } from "../../domain/purchase-repository.port";
import { accountingService } from "../../../accounting/accounting-container";

export class PurchaseAccountingGatewayAdapter implements IAccountingGateway {
    async createJournal(params: {
        description: string;
        referenceType: string;
        referenceId: string;
        lines: { accountId: string; debit: number; credit: number; description?: string }[];
        isAutoGenerated?: boolean;
    }, userId?: string, dbOrTx?: DBContext): Promise<string> {
        return await accountingService.createJournal(params, userId, dbOrTx);
    }
}
