import { TransactionContext } from "../../../../../shared/types/db-context";
import { IJournalRepository, IAccountRepository } from "../../domain";
import { AuditService } from "../../services/audit.service";

export interface JournalLineInput {
    accountId: string;
    debit: number;
    credit: number;
    description?: string | null | undefined;
}

export interface CreateJournalInput {
    date?: Date | null | undefined;
    description: string;
    referenceType?: string | null | undefined;
    referenceId?: string | null | undefined;
    lines: JournalLineInput[];
    isAutoGenerated?: boolean | undefined;
    createdBy?: string | null | undefined;
}

export class CreateJournalUseCase {
    constructor(
        private readonly journalRepository: IJournalRepository,
        private readonly accountRepository: IAccountRepository
    ) { }

    async execute(tenantId: string, input: CreateJournalInput, tx: TransactionContext, userId?: string): Promise<string> {
        const totalDebit = input.lines.reduce((sum, line) => sum + line.debit, 0);
        const totalCredit = input.lines.reduce((sum, line) => sum + line.credit, 0);

        // Tolerance for floating point
        if (Math.abs(totalDebit - totalCredit) > 0.01) {
            throw new Error(`Journal entry not balanced: Debit ${totalDebit} != Credit ${totalCredit}`);
        }

        if (input.lines.length < 2) {
            throw new Error("Journal entry must have at least 2 lines");
        }

        // Generate ID logic is usually in the repo or a domain service. 
        // Here we'll let the repo handle it or pass it.
        const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, "");
        const prefix = `JRN-${dateStr}`;
        const count = await this.journalRepository.countToday(tenantId, prefix, tx);
        const journalId = `${prefix}-${String(count + 1).padStart(3, "0")}`;

        await this.journalRepository.create(tenantId, {
            id: journalId,
            date: input.date || new Date(),
            description: input.description,
            referenceType: input.referenceType,
            referenceId: input.referenceId,
            status: "posted",
            totalDebit,
            totalCredit,
            isAutoGenerated: input.isAutoGenerated ?? true,
            createdBy: userId || input.createdBy,
            postedBy: userId || input.createdBy,
            postedAt: new Date(),
        }, tx);

        for (const line of input.lines) {
            await this.journalRepository.createLine(tenantId, {
                journalId,
                accountId: line.accountId,
                debit: line.debit,
                credit: line.credit,
                description: line.description,
            }, tx);

            await this.updateAccountBalance(tenantId, line.accountId, line.debit, line.credit, tx);
        }

        await AuditService.log(tenantId, {
            userId,
            action: "CREATE",
            entityType: "journal",
            entityId: journalId,
            tableName: "journals",
            newValues: { description: input.description, total: totalDebit, referenceType: input.referenceType },
        }, tx);

        return journalId;
    }

    private async updateAccountBalance(tenantId: string, accountId: string, debit: number, credit: number, tx: TransactionContext): Promise<void> {
        const account = await this.accountRepository.findById(tenantId, accountId, tx);
        if (!account) throw new Error(`Account ${accountId} not found`);

        const isDebitNormal = account.typeId === "ASSET" || account.typeId === "EXPENSE";
        const netChange = isDebitNormal ? (debit - credit) : (credit - debit);

        await this.accountRepository.incrementBalance(tenantId, accountId, netChange, tx);
    }
}
