import { TransactionContext } from "../../../../../shared/types/db-context";
import { ICashRegisterRepository } from "../../domain";
import { CreateJournalUseCase } from "./create-journal.use-case";
import { AuditService } from "../../services/audit.service";

export interface RecordCashExpenseInput {
    amount: number;
    description: string;
    category: string;
    accountId?: string | null | undefined; // Target expense account
    userRoles?: string[] | null | undefined;
}

export class RecordCashExpenseUseCase {
    constructor(
        private readonly registerRepository: ICashRegisterRepository,
        private readonly createJournalUC: CreateJournalUseCase
    ) { }

    async execute(tenantId: string, input: RecordCashExpenseInput, userId: string, tx: TransactionContext): Promise<void> {
        const current = await this.registerRepository.getCurrent(tenantId, tx);
        if (!current) {
            throw new Error("No open cash register found. Please open one first.");
        }

        const transactionId = `TXN-${Date.now()}`;

        // 1. Record in cash register transactions
        await this.registerRepository.createTransaction(tenantId, {
            id: transactionId,
            registerId: current.id,
            type: "expense",
            amount: input.amount,
            description: `Expense: ${input.category} - ${input.description}`,
            createdAt: new Date(),
        }, tx);

        // 2. Create Journal Entry (Debit Expense, Credit Cash)
        const expenseAccountId = input.accountId || "5-5900"; // Default to Misc Expense
        const cashAccountId = "1-1101"; // Default to Shop Cash

        await this.createJournalUC.execute(tenantId, {
            description: `Cash Register Expense: ${input.description}`,
            referenceType: "expense",
            referenceId: current.id,
            lines: [
                { accountId: expenseAccountId, debit: input.amount, credit: 0, description: input.description },
                { accountId: cashAccountId, debit: 0, credit: input.amount, description: input.description },
            ],
            isAutoGenerated: true,
        }, tx, userId);

        await AuditService.log(tenantId, {
            userId,
            action: "CREATE" as any,
            entityType: "cash_transaction",
            entityId: transactionId,
            tableName: "cash_register_transactions",
            newValues: { amount: input.amount, description: input.description },
        }, tx);
    }
}
