export type JournalReferenceType = "sale" | "purchase" | "expense" | "service" | "depreciation" | "commission" | "supplier_payment" | "adjustment" | "asset_purchase" | "manual";

export type AccountType = "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";

export interface Account {
    id: string;
    code: string;
    name: string;
    typeId: AccountType;
    parentId?: string;
    description?: string;
    isActive: boolean;
    isSystem: boolean;
    balance: number;
    createdAt: Date;
    updatedAt: Date;
}

export type JournalStatus = "draft" | "posted" | "voided";

export interface JournalEntry {
    id: string;
    date: Date;
    description: string;
    referenceType?: string;
    referenceId?: string;
    status: JournalStatus;
    totalDebit: number;
    totalCredit: number;
    isAutoGenerated: boolean;
    createdBy?: string;
    postedBy?: string;
    postedAt?: Date;
    voidedBy?: string;
    voidedAt?: Date;
    voidReason?: string;
    createdAt: Date;
    updatedAt: Date;
    lines?: JournalLine[];
}

export interface JournalLine {
    id: number;
    journalId: string;
    accountId: string;
    debit: number;
    credit: number;
    description?: string;
    accountName?: string;
    accountCode?: string;
}
