import { db } from "../../../db";
import { commissionPayments, services, users } from "../../../db/schema";
import { eq, and, desc, sql, gte, lte, isNull } from "drizzle-orm";
import { accountingService } from "../accounting-container";
import { ICommissionPaymentRepository } from "../domain";

const commissionRepository = (accountingService as any).commissionRepository as ICommissionPaymentRepository;

export interface CreateCommissionPaymentInput {
    technicianId: string;
    period: string;
    serviceIds: string[];
    amount: number;
    accountId?: string;
}

export class CommissionPaymentService {
    /**
     * Get pending commissions by technician for a period
     */
    static async getPendingCommissions(period: string) {
        const startDate = new Date(`${period}-01`);
        const endDate = new Date(startDate);
        endDate.setMonth(endDate.getMonth() + 1);

        // Get all completed services in this period
        const completedServices = await db
            .select({
                id: services.id,
                no: services.no,
                technicianId: services.technicianId,
                technicianName: users.name,
                actualCost: services.actualCost,
                parts: services.parts,
                dateOut: services.dateOut,
                commissionConfig: users.commissionConfig,
            })
            .from(services)
            .leftJoin(users, eq(services.technicianId, users.id))
            .where(and(
                gte(services.dateOut, startDate),
                lte(services.dateOut, endDate),
                eq(services.status, "diambil")
            ));

        // Get already paid service IDs for this period
        const paidCommissions = await db
            .select()
            .from(commissionPayments)
            .where(eq(commissionPayments.period, period));

        const paidServiceIds = new Set<string>();
        for (const pc of paidCommissions) {
            for (const sid of (pc.serviceIds || [])) {
                paidServiceIds.add(sid);
            }
        }

        // Filter out already paid services and group by technician
        const pendingByTechnician: Record<string, {
            technicianId: string;
            technicianName: string;
            services: (typeof completedServices)[0][];
            totalAmount: number;
        }> = {};

        for (const svc of completedServices) {
            if (!svc.technicianId || paidServiceIds.has(svc.id)) continue;

            if (!pendingByTechnician[svc.technicianId]) {
                pendingByTechnician[svc.technicianId] = {
                    technicianId: svc.technicianId,
                    technicianName: svc.technicianName || "Unknown",
                    services: [],
                    totalAmount: 0,
                };
            }

            // Special Commission Calculation:
            // (Service Price - Spare Part Selling Price) * Commission %

            const servicePrice = svc.actualCost || 0;
            let partsSellingPrice = 0;

            if (svc.parts && Array.isArray(svc.parts)) {
                for (const part of svc.parts as any[]) {
                    // Assuming part.price is the selling price charged to customer
                    // If part.price is missing, fallback to 0 to avoid NaN
                    const price = Number(part.price) || 0;
                    const qty = Number(part.qty) || 1;
                    partsSellingPrice += price * qty;
                }
            }

            const netServiceRevenue = Math.max(0, servicePrice - partsSellingPrice);

            // Get Commission Rate
            // Default 10% if not configured
            let rate = 10;
            const config = svc.commissionConfig as any;
            if (config && config.rate !== undefined) {
                rate = Number(config.rate);
            }

            const commission = Math.floor(netServiceRevenue * (rate / 100));

            pendingByTechnician[svc.technicianId].services.push(svc);
            pendingByTechnician[svc.technicianId].totalAmount += commission;
        }

        return Object.values(pendingByTechnician);
    }

    static async payCommission(input: CreateCommissionPaymentInput, userId: string): Promise<string> {
        const accountId = input.accountId || "1-1001"; // Default: Kas Toko

        // Create journal entry via facade
        await accountingService.createJournal({
            description: `Komisi teknisi ${input.period}`,
            referenceType: "commission",
            referenceId: input.technicianId,
            lines: [
                { accountId: "5-2005", debit: input.amount, credit: 0, description: "Beban komisi" },
                { accountId, debit: 0, credit: input.amount, description: "Pembayaran kas" },
            ],
            isAutoGenerated: true
        }, userId);

        const journalId = `JRN-COM-${Date.now()}`;

        // Insert payment record via repo
        const { id } = await commissionRepository.create({
            technicianId: input.technicianId,
            period: input.period,
            serviceIds: input.serviceIds,
            amount: input.amount,
            status: "paid",
            paidBy: userId,
            paidAt: new Date(),
            journalId,
            accountId,
        });

        return id;
    }

    /**
     * Get commission payment history
     */
    static async getPaymentHistory(technicianId?: string, period?: string) {
        const conditions = [];
        if (technicianId) conditions.push(eq(commissionPayments.technicianId, technicianId));
        if (period) conditions.push(eq(commissionPayments.period, period));

        const query = db
            .select({
                id: commissionPayments.id,
                technicianId: commissionPayments.technicianId,
                technicianName: users.name,
                period: commissionPayments.period,
                amount: commissionPayments.amount,
                status: commissionPayments.status,
                serviceCount: sql<number>`json_array_length(${commissionPayments.serviceIds})`,
                paidAt: commissionPayments.paidAt,
            })
            .from(commissionPayments)
            .leftJoin(users, eq(commissionPayments.technicianId, users.id))
            .orderBy(desc(commissionPayments.paidAt));

        if (conditions.length > 0) {
            return query.where(and(...conditions));
        }

        return query;
    }

    /**
     * Get summary for a period
     */
    static async getPeriodSummary(period: string) {
        const pending = await this.getPendingCommissions(period);
        const paid = await this.getPaymentHistory(undefined, period);

        return {
            period,
            pendingCount: pending.length,
            pendingTotal: pending.reduce((s, p) => s + p.totalAmount, 0),
            paidCount: paid.length,
            paidTotal: paid.reduce((s, p) => s + p.amount, 0),
        };
    }
}
