import { db } from "../../../db";
import { journals, journalLines, accounts } from "../../../db/schema";
import { eq, and, gte, lte, desc, sql } from "drizzle-orm";
import { AuditService } from "./audit.service";
import { JournalModel } from "../models/journal.model";
import { AccountModel } from "../models/accounts.model";

export type JournalReferenceType = "sale" | "purchase" | "expense" | "service" | "depreciation" | "commission" | "supplier_payment" | "adjustment" | "asset_purchase";

export interface JournalLineInput {
    accountId: string;
    debit: number;
    credit: number;
    description?: string;
}

export interface CreateJournalInput {
    date?: Date;
    description: string;
    referenceType?: JournalReferenceType;
    referenceId?: string;
    lines: JournalLineInput[];
    isAutoGenerated?: boolean;
    createdBy?: string;
}

export interface JournalFilters {
    startDate?: string;
    endDate?: string;
    referenceType?: JournalReferenceType;
    referenceId?: string;
    status?: "draft" | "posted" | "voided";
    limit?: number;
    offset?: number;
}

export class JournalService {
    /**
     * Generate a unique journal ID
     */
    private static async generateId(dbOrTx?: any): Promise<string> {
        const today = new Date();
        const dateStr = today.toISOString().slice(0, 10).replace(/-/g, "");
        const prefix = `JRN-${dateStr}`;

        const count = await JournalModel.countToday(prefix, dbOrTx);
        const num = count + 1;
        return `${prefix}-${String(num).padStart(3, "0")}`;
    }

    /**
     * Create a new journal entry with validation
     */
    static async create(input: CreateJournalInput, userId?: string, dbOrTx?: any): Promise<string> {
        // Validate double-entry: total debits must equal total credits
        const totalDebit = input.lines.reduce((sum, line) => sum + line.debit, 0);
        const totalCredit = input.lines.reduce((sum, line) => sum + line.credit, 0);

        if (totalDebit !== totalCredit) {
            throw new Error(`Journal entry not balanced: Debit ${totalDebit} != Credit ${totalCredit}`);
        }

        if (input.lines.length < 2) {
            throw new Error("Journal entry must have at least 2 lines");
        }

        const effectiveDb = dbOrTx || db;
        return await effectiveDb.transaction(async (tx: any) => {
            const journalId = await this.generateId(tx);

            // Insert journal header
            await JournalModel.create({
                id: journalId,
                date: input.date || new Date(),
                description: input.description,
                referenceType: input.referenceType,
                referenceId: input.referenceId,
                status: "posted",
                totalDebit,
                totalCredit,
                isAutoGenerated: input.isAutoGenerated ?? true,
                createdBy: userId || input.createdBy,
                postedBy: userId || input.createdBy,
                postedAt: new Date(),
            }, tx);

            // Insert journal lines
            for (const line of input.lines) {
                await JournalModel.createLine({
                    journalId,
                    accountId: line.accountId,
                    debit: line.debit,
                    credit: line.credit,
                    description: line.description,
                }, tx);

                // Update account balance
                await this.updateAccountBalance(line.accountId, line.debit, line.credit, tx);
            }

            // Audit log
            await AuditService.log({
                userId,
                action: "CREATE",
                entityType: "journal",
                entityId: journalId,
                tableName: "journals",
                newValues: { description: input.description, total: totalDebit, referenceType: input.referenceType },
            });

            return journalId;
        });
    }

    /**
     * Update account balance based on debit/credit
     */
    private static async updateAccountBalance(
        accountId: string,
        debit: number,
        credit: number,
        dbOrTx?: any
    ): Promise<void> {
        const account = await AccountModel.findById(accountId, dbOrTx);

        if (!account) {
            throw new Error(`Account ${accountId} not found`);
        }

        const isDebitNormal = account.typeId === "ASSET" || account.typeId === "EXPENSE";
        const netChange = isDebitNormal ? (debit - credit) : (credit - debit);

        await AccountModel.update(accountId, {
            balance: sql`${accounts.balance} + ${netChange}`,
            updatedAt: new Date(),
        }, dbOrTx);
    }

    /**
     * Void a journal entry (reverse its effects)
     */
    static async void(journalId: string, reason: string, userId: string, dbOrTx?: any): Promise<void> {
        const journal = await this.getById(journalId, dbOrTx);

        if (!journal) {
            throw new Error(`Journal ${journalId} not found`);
        }

        if (journal.status === "voided") {
            throw new Error("Journal is already voided");
        }

        const effectiveDb = dbOrTx || db;
        await effectiveDb.transaction(async (tx: any) => {
            // Reverse the account balances
            for (const line of journal.lines) {
                await this.updateAccountBalance(line.accountId, line.credit, line.debit, tx);
            }

            // Update journal status
            await JournalModel.update(journalId, {
                status: "voided",
                voidedBy: userId,
                voidedAt: new Date(),
                voidReason: reason,
            }, tx);
        });

        // Audit log
        await AuditService.log({
            userId,
            action: "VOID",
            entityType: "journal",
            entityId: journalId,
            tableName: "journals",
            oldValues: { status: journal.status },
            newValues: { status: "voided", voidReason: reason },
            reason,
        });
    }

    /**
     * Delete a journal and reverse its impact on account balances
     */
    static async delete(journalId: string, userId?: string, dbOrTx?: any): Promise<void> {
        const journal = await this.getById(journalId, dbOrTx);
        if (!journal) {
            throw new Error(`Journal ${journalId} not found`);
        }

        const effectiveDb = dbOrTx || db;
        await effectiveDb.transaction(async (tx: any) => {
            // Only reverse balance if it was posted
            if (journal.status === "posted") {
                for (const line of journal.lines) {
                    await this.updateAccountBalance(line.accountId, line.credit, line.debit, tx);
                }
            }

            // Delete journal (lines will cascade)
            await JournalModel.delete(journalId, tx);
        });

        // Audit log
        await AuditService.log({
            userId,
            action: "DELETE",
            entityType: "journal",
            entityId: journalId,
            tableName: "journals",
            oldValues: journal,
        });
    }

    /**
     * Delete journals by reference
     */
    static async deleteByReference(referenceType: string, referenceId: string, userId?: string, dbOrTx?: any): Promise<void> {
        const effectiveDb = dbOrTx || db;
        const matchingJournals = await effectiveDb
            .select({ id: journals.id })
            .from(journals)
            .where(
                and(
                    eq(journals.referenceType, referenceType),
                    eq(journals.referenceId, referenceId)
                )
            );

        for (const j of matchingJournals) {
            await this.delete(j.id, userId, effectiveDb);
        }
    }

    /**
     * Get journals with filters
     */
    static async getAll(filters: JournalFilters = {}, dbOrTx?: any) {
        return JournalModel.findAll(filters, dbOrTx);
    }

    /**
     * Get a journal with its lines
     */
    static async getById(journalId: string, dbOrTx?: any) {
        return JournalModel.findById(journalId, dbOrTx);
    }
}
